### ISSUE TITLE
ERROR: EXCEPTION Thrown

### ISSUE THREAD

**Issue by Skoaler** [wackerl91/luna#15]
Hey Wackerl91,

ich habe die neuste OSMC Version drauf, Moonlight Embedded ist installiert aber irgendwie komme ich nicht weiter... Bis zum pairen bin ich gekommen, ich wähle denn reiter Games und es kommt die Meldung. " Für mehr Informationen Logfile einsehen".

In welcher folgendes steht.

00:19:59  58.793304 T:1556083744  NOTICE: [script.luna] Launching Luna
00:19:59  58.813099 T:1556083744  NOTICE: [xbmcswift2] Request for "/games" matches rule for function "show_games"
00:20:00  60.272774 T:1556083744  NOTICE: [script.luna] World of Warcraft
00:20:00  60.274258 T:1556083744  NOTICE: [script.luna] Star Wars Battlefront
00:20:00  60.277927 T:1556083744  NOTICE: [script.luna] Battlefield 4
00:20:00  60.278603 T:1556083744  NOTICE: [script.luna] Grand Theft Auto V
00:20:00  60.279182 T:1556083744  NOTICE: [script.luna] Steam
00:20:00  60.279739 T:1556083744  NOTICE: [script.luna] Done getting games from moonlight
00:20:02  62.057907 T:1556083744   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'xml.etree.ElementTree.ParseError'>
                                            Error Contents: no element found: line 6732, column 412
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/luna-master/addon.py", line 416, in <module>
                                                plugin.run()
                                              File "/home/osmc/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "/home/osmc/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/home/osmc/.kodi/addons/luna-master/addon.py", line 240, in show_games
                                                get_games()
                                              File "/home/osmc/.kodi/addons/luna-master/addon.py", line 327, in get_games
                                                game_storage[game_name] = scraper.query_game_information(game_name)
                                              File "/home/osmc/.kodi/addons/luna-master/resources/lib/scraperchain.py", line 16, in query_game_information
                                                game_info.append(Game.from_dict(**scraper.get_game_information(game_name)))
                                              File "/home/osmc/.kodi/addons/luna-master/resources/lib/scraper/tgdbscraper.py", line 20, in 						get_game_information
                                                response = self._gather_information(request_name)
                                              File "/home/osmc/.kodi/addons/luna-master/resources/lib/scraper/tgdbscraper.py", line 30, in 						_gather_information
                                                xml_root = ElementTree(file=xml_response_file).getroot()
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 611, in __init__
                                                self.parse(file)
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 657, in parse
                                                self._root = parser.close()
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1654, in close
                                                self._raiseerror(v)
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
                                                raise err
                                            ParseError: no element found: line 6732, column 412
                                            -->End of Python script error report<--

Ich hoffe es ist OKay das ich auf Deutsch schreibe, habe gesehen das du aus münchen kommst.

Frohe Feiertage
Skoaler

**Comment by wackerl91** [comment]
Heya @Skoaler,
we should keep it in English, just in case someone else stumbles upon this when trying to resolve an issue they're experiencing :)
In short, it'd be best to stick to the [released versions](https://github.com/wackerl91/luna/releases) for now. I'm currently not at home so I had to do every recent feature completely blind. The released versions on the other hand are better tested. Additionally (if your problem using the scrapers persists) you can disable this feature in settings > cache control.

I'm currently preparing a new release which will be available before the end of the year and will make the scraper feature way more stable than it is right now. Sorry for the inconvenience caused. I'll leave this issue open for the next 24 hours so you can ask additional questions if necessary.

Merry Christmas!

**Comment by agboom** [comment]
I have a similar error:

```
18:16:27  56.751717 T:1601172512  NOTICE: [script.luna] Done getting games from moonlight                                                                      
18:16:28  56.921989 T:1601172512   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--                                                                     
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                                                                   
                                            Error Type: <type 'exceptions.TypeError'>                                                                          
                                            Error Contents: 'NoneType' object does not support item assignment                                                 
                                            Traceback (most recent call last):                                                                                 
                                              File "/home/osmc/.kodi/addons/luna-master/addon.py", line 416, in <module>                                       
                                                plugin.run()                                                                                                   
                                              File "/home/osmc/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run               
                                                items = self._dispatch(self.request.path)                                                                      
                                              File "/home/osmc/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch         
                                                listitems = view_func(**items)                                                                                 
                                              File "/home/osmc/.kodi/addons/luna-master/addon.py", line 240, in show_games                                     
                                                get_games()                                                                                                    
                                              File "/home/osmc/.kodi/addons/luna-master/addon.py", line 327, in get_games                                      
                                                game_storage[game_name] = scraper.query_game_information(game_name)                                            
                                              File "/home/osmc/.kodi/addons/luna-master/resources/lib/scraperchain.py", line 16, in query_game_information     
                                                game_info.append(Game.from_dict(**scraper.get_game_information(game_name)))                                    
                                              File "/home/osmc/.kodi/addons/luna-master/resources/lib/scraper/omdbscraper.py", line 19, in get_game_information
                                                response['name'] = game_name                              
                                            TypeError: 'NoneType' object does not support item assignment 
                                            -->End of Python script error report<--                       
18:16:28  57.091465 T:1957790256   ERROR: GetDirectory - Error getting plugin://script.luna/games         
18:16:28  57.091854 T:1957790256   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.luna/games) failed
```

I have an NVidia GTX 960, if that helps. If you need anymore information, let me know.

**Comment by wackerl91** [comment]
@agboom Those two issues are not related at all. @Skoaler's issue is pretty much a 'this should never happen case' while yours is just me forgetting about a possible None value in that function ;)  Apart from that, it has already been fixed since v0.3.0-alpha. Please make sure to update Luna and (if it shouldn't work afterwards) open a new issue if necessary.
Thanks for the report though and I hope the latest update resolves the problem you were experiencing.
Cheers!

**Comment by agboom** [comment]
Sorry, should've looked closer, I see now that the stack traces point to different scrapers. The error seemed similar at first glance. I updated and the error is gone, though a different error popped up.

**Comment by wackerl91** [comment]
No worries, that's fine - just want to keep things organized a bit.

@Skoaler:
I've been trying to reproduce your issue a few times now and .. I just can't. Could you provide me with some additional information? Which Luna version were you using when you ran into it? Are you using a wired or a wireless connection?

**Comment by Skoaler** [comment]
@wackerl91 
Hey, 
after 3 days Raspberry Pi , Moonlight and Retropi configuration i have a lot of Brain lags (Linux noob)  and no longer knows exactly how the error has come to pass. I think I have a version develop or otherwise installed . I now use the V. 0.2.2 and finally got to the Xbox360 controller to run. In Moonlight and Rettropie . In Kodi unfortunately it is not working .
I'm like V. 0.2.2 . I test in the next few days times V. 0.3.0 .

Let's see , my head tells me
"Never touch a running system " = D

Have a nice day and sorry for my english creepy .

**Comment by wackerl91** [comment]
Well, master is a bit ... nondescriptive, as this is always the latest code pushed to that branch (which is not necessarily the same as a released version).
If you feel more comfortable talking about this in German just send me a message at [OSMC forums](https://discourse.osmc.tv/users/exxe/activity) :)

**Comment by wackerl91** [comment]
Since there hasn't been any more information regarding this issue (and no steps to reproduce) for over a month now and I couldn't reproduce it on my machines this is now closed.
If anyone runs into the same issue in the future just reopen it.
