### ISSUE TITLE
Luna Launch error

### ISSUE THREAD

**Issue by Spitwod** [wackerl91/luna#72]
Looking for some help with my OSMC Moonlight with Hyperion rig.
I have moonlight-embedded installed and I can get it to work from from the old limelight scripts.
However I was looking for a more user friendly method and Luna seemed to fit what I am looking for.

I am getting the following errors in the kodi.log when launching the addon (after configuring it with just my host IP and pairing successfully)

`21:33:22 1144.579834 T:1650455536  NOTICE: [script.luna] [CoreService] - initialized
21:33:24 1146.679810 T:1650455536   ERROR: /home/osmc/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
                                              InsecureRequestWarning)
21:33:24 1146.717773 T:1650455536  NOTICE: [script.luna] Trying to re-encode received XML as UTF-16
21:33:24 1146.756958 T:1650455536   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'xml.etree.ElementTree.ParseError'>
                                            Error Contents: not well-formed (invalid token): line 1, column 1
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.luna/addon.py", line 203, in <module>
                                                game_controller.get_games()
                                              File "/home/osmc/.kodi/addons/script.luna/resources/lib/controller/gamecontroller.py", line 18, in get_games
                                                game_list = self.moonlight_helper.list_games()
                                              File "/home/osmc/.kodi/addons/script.luna/resources/lib/util/moonlighthelper.py", line 135, in list_games
                                                return RequiredFeature('nvhttp').request().get_app_list()
                                              File "/home/osmc/.kodi/addons/script.luna/resources/lib/nvhttp/nvhttp.py", line 146, in get_app_list
                                                applist = self.get_app_list_from_string(response.content)
                                              File "/home/osmc/.kodi/addons/script.luna/resources/lib/nvhttp/nvhttp.py", line 151, in get_app_list_from_string
                                                applist_root = ET.ElementTree(ET.fromstring(self.re_encode_string(xml_string))).getroot()
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
                                                parser.feed(text)
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
                                                self._raiseerror(v)
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
                                                raise err
                                            ParseError: not well-formed (invalid token): line 1, column 1
                                            -->End of Python script error report<--
21:33:24 1146.985718 T:1956860848   ERROR: GetDirectory - Error getting plugin://script.luna/
21:33:24 1146.986206 T:1956860848   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.luna/) failed`

**Comment by wackerl91** [comment]
@Spitwod 
This is literally the same issue as #71. Try using the previous version until I find time to fix this.
